mayu0506/freemarket_sample_50dn

- app/assets/stylesheets/style.scss
> Edit.add-common-set-up-scss

- README.md
- config/initializers/inflections.rb
・データベースの設計
・Read.me
・前もって必要なデータベースを洗い出し、作業をスムーズに行うため。
・不可算名詞のテーブル名に関しては、
「config/initializers/inflections.rb」に不可算名詞と記載し、不可算名詞のまま使用できるように設定
> Edit-add-read-me

- Gemfile
- Gemfile.lock
> Edit.add-gem-rspec

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/config/colors.scss
- app/assets/stylesheets/modules/_product-header.scss
- app/assets/stylesheets/modules/_product-index.scss
- app/assets/stylesheets/modules/_sell-btn.scss
- app/views/layouts/application.html.haml
- app/views/products/_product-header.html.haml
- app/views/products/_sell-btn.html.haml
- app/views/products/index.html.haml
- config/database.yml
> product-index html

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/config/card-image.scss
- app/assets/stylesheets/modules/card-page.scss
- app/controllers/payments_controller.rb
- app/views/payments/index.html.haml
- app/views/payments/new.html.haml
- app/views/products/new.html.haml
- app/views/users/_eachpage-footer.html.haml
- app/views/users/_eachpage-header.html.haml
- app/views/users/new.html.haml
- config/routes.rb
[![Image from Gyazo](https://i.gyazo.com/73c385ff5efe077c5e970ba631ccdc01.png)](https://gyazo.com/73c385ff5efe077c5e970ba631ccdc01)
[![Image from Gyazo](https://i.gyazo.com/9c3cf705105dc995f9ecfb469104f31a.png)](https://gyazo.com/9c3cf705105dc995f9ecfb469104f31a)
クレジットカード情報の登録画面を作成した
ユーザが商品をクレジットカードを使って購入する際に必要な情報であるため
> クレジットカード情報登録画面の作成

- app/assets/stylesheets/login/login.scss
- app/assets/stylesheets/modules/login/login.scss
- app/assets/stylesheets/registration/address.scss
- app/assets/stylesheets/registration/authentication.scss
- app/assets/stylesheets/registration/completed.scss
- app/assets/stylesheets/registration/information.scss
- app/assets/stylesheets/registration/payment.scss
- app/assets/stylesheets/registration/phone_number.scss
- app/views/users/login/login.html.haml
- app/views/users/registration/address.html.haml
- app/views/users/registration/authentication.html.haml
- app/views/users/registration/completed.html.haml
- app/views/users/registration/information.html.haml
- app/views/users/registration/payment.html.haml
- app/views/users/registration/phone_number.html.haml
新規登録ページ及びログインページの作成
ユーザー管理に必要な為
[![Image from Gyazo](https://i.gyazo.com/89668359fde4595748361ba493122586.png)](https://gyazo.com/89668359fde4595748361ba493122586)
[![Image from Gyazo](https://i.gyazo.com/4289c720e011bfff69df0709b3eb2757.png)](https://gyazo.com/4289c720e011bfff69df0709b3eb2757)
[![Image from Gyazo](https://i.gyazo.com/b686a8d959d13724fc29094526decfe6.png)](https://gyazo.com/b686a8d959d13724fc29094526decfe6)
[![Image from Gyazo](https://i.gyazo.com/4bc8cef08b66d9f6e1436fbe0fa6626c.png)](https://gyazo.com/4bc8cef08b66d9f6e1436fbe0fa6626c)
[![Image from Gyazo](https://i.gyazo.com/7a01af24328f1349de26ba80c67232c9.png)](https://gyazo.com/7a01af24328f1349de26ba80c67232c9)
[![Image from Gyazo](https://i.gyazo.com/8960ba93e1a5a86c3a8a3746f7d16579.png)](https://gyazo.com/8960ba93e1 …
> add-registration-and-login

- README.md
> Edit.edit-product-table

- app/models/brand.rb
- app/models/product.rb
- db/migrate/20190507064507_devise_create_users.rb
- db/migrate/20190513122555_create_products.rb
- db/migrate/20190513125534_create_brands.rb
- db/schema.rb
productモデルの状態はdown。
productモデルの内容はmigrateファイルに記載のまま。
※brandは使用しない。→名前変更します。
> Add product model

- README.md
[what]
機能実装
foreign_key
[why]
必須
> add buyer_id    seller_id

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/modules/_product-header.scss
- app/controllers/products_controller.rb
- app/views/devise/sessions/new.html.haml
- app/views/products/_product-header.html.haml
- app/views/products/buy.html.haml
- app/views/products/new.html.haml
- app/views/users/login/login.html.haml
> Edit.sign-in-server

- app/models/product.rb
- db/schema.rb
> create product database

- app/assets/stylesheets/registration/information.scss
- app/controllers/application_controller.rb
- app/controllers/users/registrations_controller.rb
- app/models/user.rb
- app/views/devise/registrations/complete.html.haml
- app/views/devise/registrations/index.html.haml
- app/views/devise/registrations/new.html.haml
- app/views/products/_product-header.html.haml
- app/views/users/registration/completed.html.haml
- config/routes.rb
- db/migrate/20190515114001_remove_birth_year_from_user.rb
- db/migrate/20190515114305_remove_birth_month_from_user.rb
- db/migrate/20190515114354_remove_birth_date_from_user.rb
- db/migrate/20190515122514_remove_introduction_from_user.rb
- db/schema.rb
> edit-registration-server

- db/migrate/20190516041529_change_type_string_to_int_product.rb
- db/schema.rb
[what]
カラム
condition
who_to_pay
origin_of_delivery
deliverying_date
型
string → integer
[why]
商品購入時create時扱いやすくするため
> product string→integer

- Gemfile.lock
- app/controllers/users/registrations_controller.rb
- app/views/devise/registrations/complete.html.haml
- app/views/devise/registrations/new.html.haml
- app/views/devise/sessions/new.html.haml
- app/views/products/_product-header.html.haml
> Edit.signed_in3

- app/assets/stylesheets/login/login.scss
- app/assets/stylesheets/modules/coElements.scss
- app/views/devise/sessions/new.html.haml
> Edit.sign-in-view

- Gemfile
- Gemfile.lock
- README.md
- app/views/products/_product-header.html.haml
- app/views/users/_side.html.haml
- db/migrate/20190517075324_create_addresses.rb
- db/schema.rb
jp-prefectureというgemの導入
addressesテーブルの作成
都道府県のintegerでの登録がすごく楽になるから
公式ドキュメントhttps://github.com/chocoby/jp_prefecture
addressesテーブルにuserの住所を登録するため
そのほか細かい修正してあります。
> Gem導入とaddressesテーブルの作成

- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
[what]
test database使用時createしたデータをリセット
> databese cleaner

- app/controllers/users/registrations_controller.rb
> Edi-sns-registrations

- Gemfile
- Gemfile.lock
- app/controllers/products_controller.rb
- app/views/products/_product-header.html.haml
- app/views/products/_products-search.html.haml
- app/views/products/search.html.haml
- config/application.rb
- config/initializers/kaminari_config.rb
- config/locales/ja.yml
- config/routes.rb
> Edit-add-search-functions

- app/controllers/products_controller.rb
- app/models/product.rb
- db/schema.rb
- spec/controllers/products_controller_spec.rb
- spec/factories/products.rb
商品詳細ページの単体テスト
DBから正常にデータを取得し表示ができるかの確認
> Test product detail

- app/assets/stylesheets/modules/_product-header.scss
- config/locales/devise.ja.yml
> Edit.search-lv1

- config/locales/devise.ja.yml
> edit-japanese-translate

- app/assets/stylesheets/modules/_product-change.scss
- app/controllers/products_controller.rb
- app/views/products/change.html.haml
- config/routes.rb
> 商品ステータス　販売中・停止中切り替え

- app/assets/javascripts/product.js
- app/assets/stylesheets/config/colors.scss
- app/assets/stylesheets/registration/nav-bar.scss
- app/views/addresses/_address-nav-bar.html.haml
- app/views/addresses/new.html.haml
- app/views/devise/registrations/_complete-nav-bar.html.haml
- app/views/devise/registrations/_new-nav-bar.html.haml
- app/views/devise/registrations/complete.html.haml
- app/views/devise/registrations/new.html.haml
- app/views/payments/_peyment-nav-bar.html.haml
- app/views/payments/new.html.haml
新規登録ページのナビゲーションバー実装
新規登録のフローを可視化するため
[![Image from Gyazo](https://i.gyazo.com/7aa247c48018864616306974f9b1b4cd.png)](https://gyazo.com/7aa247c48018864616306974f9b1b4cd)
[![Image from Gyazo](https://i.gyazo.com/22a88c275895c4d4e2a4122a16068e7a.png)](https://gyazo.com/22a88c275895c4d4e2a4122a16068e7a)
[![Image from Gyazo](https://i.gyazo.com/522adeff3e19a262037f8961c5ef31b1.png)](https://gyazo.com/522adeff3e19a262037f8961c5ef31b1)
[![Image from Gyazo](https://i.gyazo.com/04752de791f0913a33abc86b20873da9.png)](https://gyazo.com/04752de791f0913a33abc86b20873da9)
> add-navigation-bar

- config/locales/devise.ja.yml
- spec/controllers/addresses_controller_spec.rb
- spec/controllers/user_registrations_controller_spec.rb
- spec/models/address_spec.rb
- spec/models/user_spec.rb
> edit-test-registration-model

- app/views/products/_show-item.html.haml
> edit-pdetails-view

- app/controllers/addresses_controller.rb
- app/controllers/payments_controller.rb
- app/controllers/users/registrations_controller.rb
- app/views/addresses/new.html.haml
- app/views/payments/new.html.haml
> Edit.registration-server-ver3

- app/views/products/_show-item.html.haml
> Add-prefecture

- app/assets/javascripts/product.js
> Show other

- app/views/products/_products-searchMain.html.haml
> edit-search-result

- app/assets/javascripts/select_box.js
- app/assets/javascripts/upload_image.js
- app/assets/stylesheets/modules/image_upload.scss
- app/assets/stylesheets/modules/sellcontents.scss
- app/controllers/products_controller.rb
- app/views/products/_edit.html.haml
- app/views/products/_sell.html.haml
- config/routes.rb
[![Image from Gyazo](https://i.gyazo.com/18bd32f15aea1ab0cb1900266fdd390b.gif)](https://gyazo.com/18bd32f15aea1ab0cb1900266fdd390b)
商品出品の際のカテゴリーのセレクトボックスを実装した
商品出品の際に孫カテゴリーを選択させる必要があるため
ユーザーの操作性を向上させるため
> カテゴリのセレクトボックス実装

- app/views/products/_products-searchMain.html.haml
> edit.image-tag

- README.md
- db/schema.rb
> Edit-read-me

- app/assets/stylesheets/modules/image_upload.scss
- app/assets/stylesheets/modules/sellcontents.scss
- app/views/layouts/application.html.haml
> エラーメッセージの日本語化
